packages:
  - "packages/*"
  - "apps/*"
  - "workers/*"

catalog:
  '@tailwindcss/vite': ^4.2.2
  '@testing-library/jest-dom': ^6.9.1
  '@testing-library/react': ^16.3.2
  "@types/node": ^22
  "@types/react": ^19
  "@types/react-dom": ^19
  jsdom: ^29.0.1
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwindcss: ^4.2.2
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: latest
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.13
  zustand: ^5.0.3

catalogMode: prefer

overrides:
  vite: "catalog:"
  vitest: "catalog:"

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
